ACLOCAL_AMFLAGS = -I m4

root_sbindir = "/sbin"
root_etcdir  = "/etc"
root_libdir  = "/lib"
root_datadir = "/data"

powerapp_SOURCES = powerapp.c

AM_CFLAGS = -Os \
            -g \
            -Wall \
            -Wno-unused-parameter \
            -D_XOPEN_SOURCE \
            -D_GNU_SOURCE \
            -I../include \
            @GLIB_CFLAGS@ \
            -Dstrlcpy=g_strlcpy

AM_LDFLAGS = @GLIB_LIBS@

if ENABLE_VM_POWER_CONFIG
    AM_CFLAGS += -DVM_POWER_CONFIG
endif

if USE_GLIB
AM_CFLAGS  += $(GLIB_CFLAGS) -include glib.h -Dstrlcpy=g_strlcpy
AM_LDFLAGS = $(GLIB_LIBS)
endif

powerapp_sbindir             = $(root_sbindir)
powerapp_sbin_PROGRAMS       = powerapp
powerapp_sbin_SCRIPTS        = reboot-bootloader
powerapp_sbin_SCRIPTS       += reboot-recovery

powerapp_userfsdatadir       = $(root_datadir)
powerapp_userfsdata_SCRIPTS  = reboot-cookie

if USE_SYSTEMD
powerapp_sysconfdir       = $(root_etcdir)/initscripts
powerapp_sysconf_SCRIPTS  = reboot
powerapp_sysconf_SCRIPTS += reset_reboot_cookie
powerapp_sysconf_SCRIPTS += shutdown
powerapp_sysconf_SCRIPTS += start_power_config
powerapp_sysconf_SCRIPTS += enable_autosleep

install-data-hook:
	mv $(DESTDIR)/$(powerapp_sysconfdir)/start_power_config  $(DESTDIR)/$(powerapp_sysconfdir)/power_config

powerapp_systemddir       = $(root_libdir)/systemd/system
powerapp_systemd_DATA     = reset_reboot_cookie.service
powerapp_systemd_DATA    += power_config.service
powerapp_systemd_DATA    += enable_autosleep.service
else
powerapp_sysconfdir       = $(root_etcdir)/init.d
powerapp_sysconf_SCRIPTS  = reboot
powerapp_sysconf_SCRIPTS += reset_reboot_cookie
powerapp_sysconf_SCRIPTS += shutdown
powerapp_sysconf_SCRIPTS += start_power_config
powerapp_sysconf_SCRIPTS += enable_autosleep

install-data-hook:
	 mv $(DESTDIR)/$(powerapp_sysconfdir)/start_power_config $(DESTDIR)/$(powerapp_sysconfdir)/power_config

endif
