#! /bin/sh
#
# Copyright (c) 2011-2014, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# PM Configuration

enable_lemur_ftrace_event_tracing()
{
    echo "++++ $0 -> ENABLE-FTRACE START" > /dev/kmsg
    #Enable FTRACE_ENABLE on SDXLEMUR
    #bail out if its perf config
    if [ ! -d /sys/module/msm_rtb ]
    then
        return
    fi

    #bail out if coresight isn't present
    if [ ! -d /sys/bus/coresight ]
    then
        return
    fi

    coresight
    #echo sg > /sys/bus/coresight/devices/coresight-tmc-etr/mem_type

    echo 0 > /sys/kernel/debug/tracing/events/enable
    echo mem > /sys/bus/coresight/devices/coresight-tmc-etr/out_mode
    echo 1 > /sys/bus/coresight/devices/coresight-tmc-etr/enable_sink
    echo 1 > /sys/bus/coresight/devices/coresight-stm/enable_source
    echo 1 > /sys/kernel/debug/tracing/tracing_on

    #SoftIRQs
    echo 1 > /sys/kernel/debug/tracing/events/irq/enable
    echo 1 > /sys/kernel/debug/tracing/events/irq/softirq_entry/enable
    echo 1 > /sys/kernel/debug/tracing/events/irq/softirq_exit/enable
    echo 1 > /sys/kernel/debug/tracing/events/irq/softirq_raise/enable
    #IRQs
    echo 1 > /sys/kernel/debug/tracing/events/irq/enable
    echo 1 > /sys/kernel/debug/tracing/events/irq/irq_handler_entry/enable
    echo 1 > /sys/kernel/debug/tracing/events/irq/irq_handler_exit/enable
    echo 1 > /sys/kernel/debug/tracing/events/workqueue/enable
    echo 1 > /sys/kernel/debug/tracing/events/timer/timer_expire_entry/enable
    echo 1 > /sys/kernel/debug/tracing/events/timer/timer_expire_exit/enable
    echo 1 > /sys/kernel/debug/tracing/events/timer/hrtimer_cancel/enable
    echo 1 > /sys/kernel/debug/tracing/events/timer/hrtimer_expire_entry/enable
    echo 1 > /sys/kernel/debug/tracing/events/timer/hrtimer_expire_exit/enable
    echo 1 > /sys/kernel/debug/tracing/events/timer/hrtimer_init/enable
    echo 1 > /sys/kernel/debug/tracing/events/timer/hrtimer_start/enable

    echo 1 > /sys/kernel/debug/tracing/events/sched/sched_switch/enable

    echo 1 > /sys/kernel/debug/tracing/events/clk/enable
    echo 1 > /sys/kernel/debug/tracing/events/regulator/enable
    echo 1 > /sys/kernel/debug/tracing/events/rpmh/enable

    echo 1 > /sys/kernel/debug/tracing/tracing_on
    echo "++++ $0 -> ENABLE-FTRACE END" > /dev/kmsg
}

enable_lemur_dcc_config()
{
    echo "++++ $0 -> ENABLE-DCC START" > /dev/kmsg
    DCC_PATH="/sys/bus/platform/devices/117f000.dcc_v2"
    if [ ! -d $DCC_PATH ];
    then
        echo "DCC does not exist on this build."
            return
    fi

    echo 0 > $DCC_PATH/enable
    echo 2 > $DCC_PATH/curr_list
    echo cap > $DCC_PATH/func_type
    echo sram > $DCC_PATH/data_sink
    echo 1 > $DCC_PATH/config_reset

    #Registers add space
    echo 0xb204520 1 > $DCC_PATH/config #RPMH_PDC_APPS_SEQ_START_ADDR
    echo 0xb201020 1 > $DCC_PATH/config #RPMH_PDC_APPS_SEQ_BUSY_DRV0
    echo 0xb201024 1 > $DCC_PATH/config #RPMH_PDC_APPS_SEQ_DBG_PROGRAM_COUNTER_DRV0
    echo 0xb211024 1 > $DCC_PATH/config #RPMH_PDC_APPS_SEQ_DBG_PROGRAM_COUNTER_DRV0
    echo 0xb204524 1 > $DCC_PATH/config #RPMH_PDC_APPS_SEQ_OVERRIDE_START_ADDR

    #RSC registers
    echo 0x1781002C 0x1480 > $DCC_PATH/config_write
    echo 0x17830408 1 > $DCC_PATH/config #APCS_RSCC_RSC_SEQ_PROGRAM_COUNTER_DRV0
    echo 0x17808004 1 > $DCC_PATH/config
    echo 0x17808020 1 > $DCC_PATH/config
    echo 0x1781002C 0x900 > $DCC_PATH/config_write

    echo 0xC201244 1 > $DCC_PATH/config
    echo 0xC202244 1 > $DCC_PATH/config
    echo 0xC20100C 0x9 > $DCC_PATH/config
    echo 0xC20200C 0x9 > $DCC_PATH/config

    echo 0x9690008 1 > $DCC_PATH/config
    echo 0x9690010 1 > $DCC_PATH/config
    echo 0x9693008 1 > $DCC_PATH/config
    echo 0x9693010 1 > $DCC_PATH/config
    echo 0x9698008 1 > $DCC_PATH/config
    echo 0x9698010 1 > $DCC_PATH/config
    #echo 0x969A008 1 > $DCC_PATH/config
    echo 0x969A010 1 > $DCC_PATH/config
    echo 0x969B008 1 > $DCC_PATH/config
    echo 0x969B010 1 > $DCC_PATH/config

    #MEMNOC_HM_mem_noc_debug_master
    echo 0x9685100 1 > $DCC_PATH/config
    echo 0x9685104 1 > $DCC_PATH/config
    echo 0x968510C 1 > $DCC_PATH/config
    echo 0x9685110 1 > $DCC_PATH/config
    echo 0x9685114 1 > $DCC_PATH/config
    echo 0x9685300 1 > $DCC_PATH/config
    echo 0x9685308 1 > $DCC_PATH/config
    echo 0x968530C 1 > $DCC_PATH/config
    echo 0x969E100 1 > $DCC_PATH/config
    echo 0x96A3100 1 > $DCC_PATH/config

    #MEMNOC_HM_mem_noc_errorlogger
    echo 0x9680000 1 > $DCC_PATH/config
    echo 0x9680008 1 > $DCC_PATH/config
    echo 0x9680010 1 > $DCC_PATH/config
    echo 0x9680020 7 > $DCC_PATH/config

    #MEMNOC_HM_mem_noc_sbm
    echo 0x9680440 1 > $DCC_PATH/config
    echo 0x9680448 1 > $DCC_PATH/config

    echo 0x162C008 1 > $DCC_PATH/config
    echo 0x162C010 1 > $DCC_PATH/config
    echo 0x162D008 1 > $DCC_PATH/config
    echo 0x162D010 1 > $DCC_PATH/config
    echo 0x162E008 1 > $DCC_PATH/config
    echo 0x162E010 1 > $DCC_PATH/config
    echo 0x162F008 1 > $DCC_PATH/config
    echo 0x162F010 1 > $DCC_PATH/config
    echo 0x1630008 1 > $DCC_PATH/config
    echo 0x1630010 1 > $DCC_PATH/config
    echo 0x1631008 1 > $DCC_PATH/config
    echo 0x1631010 1 > $DCC_PATH/config
    echo 0x1632008 1 > $DCC_PATH/config
    echo 0x1632010 1 > $DCC_PATH/config
    echo 0x1634008 1 > $DCC_PATH/config
    echo 0x1634010 1 > $DCC_PATH/config
    echo 0x1635008 1 > $DCC_PATH/config
    echo 0x1635010 1 > $DCC_PATH/config
    echo 0x1636008 1 > $DCC_PATH/config
    echo 0x1636010 1 > $DCC_PATH/config
    echo 0x1637008 1 > $DCC_PATH/config
    echo 0x1637010 1 > $DCC_PATH/config
    echo 0x1638008 1 > $DCC_PATH/config
    echo 0x1638010 1 > $DCC_PATH/config

    echo 0x164D100 1 > $DCC_PATH/config
    echo 0x164E100 1 > $DCC_PATH/config
    echo 0x164E104 1 > $DCC_PATH/config
    echo 0x164E108 1 > $DCC_PATH/config
    echo 0x164E10C 1 > $DCC_PATH/config
    echo 0x164E110 1 > $DCC_PATH/config
    echo 0x164F100 1 > $DCC_PATH/config
    echo 0x164F104 1 > $DCC_PATH/config
    echo 0x164F108 1 > $DCC_PATH/config
    echo 0x164F10C 1 > $DCC_PATH/config
    echo 0x1650100 1 > $DCC_PATH/config
    echo 0x1650104 1 > $DCC_PATH/config
    echo 0x1650108 1 > $DCC_PATH/config
    echo 0x165010C 1 > $DCC_PATH/config
    echo 0x1651100 1 > $DCC_PATH/config
    echo 0x1651104 1 > $DCC_PATH/config

    echo 0x1620010 1 > $DCC_PATH/config
    echo 0x1620018 1 > $DCC_PATH/config
    echo 0x1620020 1 > $DCC_PATH/config
    echo 0x1620024 1 > $DCC_PATH/config
    echo 0x1620028 1 > $DCC_PATH/config
    echo 0x162002C 1 > $DCC_PATH/config
    echo 0x1620030 1 > $DCC_PATH/config
    echo 0x1620034 1 > $DCC_PATH/config
    echo 0x1620038 1 > $DCC_PATH/config
    echo 0x162003C 1 > $DCC_PATH/config

    echo 0x1620240 1 > $DCC_PATH/config
    echo 0x1620244 1 > $DCC_PATH/config
    echo 0x1620248 1 > $DCC_PATH/config
    echo 0x162024C 1 > $DCC_PATH/config

    echo 0x117004 1 > $DCC_PATH/config
    echo 0x12F004 1 > $DCC_PATH/config
    echo 0x143004 1 > $DCC_PATH/config
    echo 0x148004 1 > $DCC_PATH/config
    #LLCC/CABO Registers
    echo 0x9220344 8 > $DCC_PATH/config
    echo 0x9220370 6 > $DCC_PATH/config
    echo 0x9220480 > $DCC_PATH/config
    echo 0x9222400 5 > $DCC_PATH/config
    echo 0x9223214 5 > $DCC_PATH/config
    echo 0x9223308 > $DCC_PATH/config
    echo 0x9223318 > $DCC_PATH/config
    echo 0x9230010 > $DCC_PATH/config
    echo 0x9230020 > $DCC_PATH/config
    echo 0x9230030 > $DCC_PATH/config
    echo 0x9230040 > $DCC_PATH/config
    echo 0x9232050 > $DCC_PATH/config
    echo 0x9232100 > $DCC_PATH/config
    echo 0x9236040 8 > $DCC_PATH/config
    echo 0x92360A0 > $DCC_PATH/config
    echo 0x92360B0 > $DCC_PATH/config
    echo 0x9238004 > $DCC_PATH/config
    echo 0x9238014 > $DCC_PATH/config
    echo 0x923805C > $DCC_PATH/config
    echo 0x923A004 7 > $DCC_PATH/config
    echo 0x923E030 2 > $DCC_PATH/config
    echo 0x9241000 > $DCC_PATH/config
    echo 0x9242028 > $DCC_PATH/config
    echo 0x9242044 3 > $DCC_PATH/config
    echo 0x9242070 > $DCC_PATH/config
    echo 0x9248030 > $DCC_PATH/config
    echo 0x9248048 8 > $DCC_PATH/config
    echo 0x9260080 > $DCC_PATH/config
    echo 0x9260400 > $DCC_PATH/config
    echo 0x9260410 5 > $DCC_PATH/config
    echo 0x9260430 > $DCC_PATH/config
    echo 0x9260440 > $DCC_PATH/config
    echo 0x9260448 > $DCC_PATH/config
    echo 0x92604A0 > $DCC_PATH/config
    echo 0x92604B0 > $DCC_PATH/config
    echo 0x92604B8 2 > $DCC_PATH/config
    echo 0x92604D0 2 > $DCC_PATH/config
    echo 0x9261400 > $DCC_PATH/config
    echo 0x9263410 > $DCC_PATH/config
    echo 0x92653B0 > $DCC_PATH/config
    echo 0x9265804 > $DCC_PATH/config
    echo 0x9265B1C > $DCC_PATH/config
    echo 0x9265B2C > $DCC_PATH/config
    echo 0x9265B38 > $DCC_PATH/config
    echo 0x9269100 > $DCC_PATH/config
    echo 0x9269110 > $DCC_PATH/config
    echo 0x9269120 > $DCC_PATH/config
    echo 0x9269108 > $DCC_PATH/config
    echo 0x9269118 > $DCC_PATH/config
    echo 0x9269180 2 > $DCC_PATH/config

    echo 0x17808100 0x9 > $DCC_PATH/config

    echo 1 > $DCC_PATH/enable

    echo "++++ $0 -> ENABLE-DCC END" > /dev/kmsg

}

set -e

case "$1" in
  start)
        soc_id=`cat /sys/devices/soc0/soc_id`

	case "$soc_id" in
	"290" | "296" | "297" | "298" | "299" | "322")
		echo -n "Starting powerconfig for mdm9607: "

		echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
		echo 40000 > /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
		echo 80 > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
		echo 998400 > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
		echo "1 806400:80" > /sys/devices/system/cpu/cpufreq/interactive/target_loads
		echo 40000 > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
		echo 806400 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
		echo mem > /sys/power/autosleep

		# Enable Low Power modes
		echo 0 > /sys/module/lpm_levels/parameters/sleep_disabled
		;;
	esac

        case "$soc_id" in
        "279" | "284" | "285" | "286" | "283")
                echo -n "Starting powerconfig for MDM9650: "

                echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
                echo 40000 > /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
                echo 90 > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
                echo 800000 > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
                echo "85 800000:90" > /sys/devices/system/cpu/cpufreq/interactive/target_loads
                echo 40000 > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
                echo 300000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
                echo mem > /sys/power/autosleep

                # Disable standalone_pc
                echo N > /sys/module/lpm_levels/system/cpu0/standalone_pc/idle_enabled
                echo N > /sys/module/lpm_levels/system/cpu0/standalone_pc/suspend_enabled

		# Enable Low Power modes
                echo N > /sys/module/lpm_levels/parameters/sleep_disabled
                ;;
        esac

        case "$soc_id" in
        "234" | "235" | "236"| "237" | "238")
                echo -n "Starting powerconfig for 9x40: "
                echo N > /sys/module/lpm_levels/parameters/sleep_disabled

                echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
                echo 40000 > /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
                echo 90 > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
                echo 800000 > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
                echo "85 800000:90" > /sys/devices/system/cpu/cpufreq/interactive/target_loads
                echo 40000 > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
                echo 300000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
                echo mem > /sys/power/autosleep
                ;;
        esac

        case "$soc_id" in
        "104" | "105" | "106" | "107")
                echo -n "Starting powerconfig for 9x15: "
                echo 1 > /sys/module/pm_8x60/modes/cpu0/power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/power_collapse/idle_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/standalone_power_collapse/idle_enabled
                echo 1 > /sys/module/rpm_resources/enable_low_power/pxo
                echo 2 > /sys/module/rpm_resources/enable_low_power/vdd_dig
                echo 2 > /sys/module/rpm_resources/enable_low_power/vdd_mem
                echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
                echo "done"
                ;;
         esac

         case "$soc_id" in
         "134" | "148" | "149" | "150" | "151" | "152" | "173" | "174" | "175")
                echo -n "Starting powerconfig for 9x25: "
                echo 1 > /sys/module/pm_8x60/modes/cpu0/power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/power_collapse/idle_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/standalone_power_collapse/idle_enabled
                echo 1 > /sys/module/lpm_resources/enable_low_power/pxo
                echo 1 > /sys/module/lpm_resources/enable_low_power/vdd_dig
                echo 675000 > /sys/module/lpm_resources/enable_low_power/vdd_mem
                echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
                echo "done";
                ;;
         esac

         case "$soc_id" in
         "333" | "314")
                echo -n "Starting powerconfig for SDX20: "
                echo N > /sys/module/lpm_levels/parameters/sleep_disabled
                # Enable LPMs
                echo Y > /sys/module/lpm_levels/system/cpu0/wfi/idle_enabled
                echo Y > /sys/module/lpm_levels/system/cpu0/standalone_pc/idle_enabled
                echo Y > /sys/module/lpm_levels/system/cpu0/pc/idle_enabled
                echo Y > /sys/module/lpm_levels/system/cpu0/wfi/suspend_enabled
                echo Y > /sys/module/lpm_levels/system/cpu0/standalone_pc/suspend_enabled
                echo Y > /sys/module/lpm_levels/system/cpu0/pc/suspend_enabled

                echo interactive >  /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
                echo 40000 > /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
                echo 90 > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
                echo 800000 > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
                echo "85 800000:90" > /sys/devices/system/cpu/cpufreq/interactive/target_loads
                echo 40000 > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
                echo 300000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

                echo mem > /sys/power/autosleep
                ;;
         esac

         case "$soc_id" in
         "334" )
                echo -n "Starting powerconfig for SDX24: "
                echo N > /sys/module/lpm_levels/parameters/sleep_disabled
                #CPU Governor settings
                echo ondemand >  /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
                #Enable Suspend
                echo mem > /sys/power/autosleep
                #Enable bus-dcvs
                echo "compute" > /sys/class/devfreq/soc:qcom,cpubw/governor
                echo 10 > /sys/class/devfreq/soc:qcom,cpubw/polling_interval

		echo "++++ $0 -> ENABLE-FTRACE" > /dev/kmsg
		#Enable FTRACE_ENABLE on SDX24
		#bail out if its perf config
		if [ ! -d /sys/module/msm_rtb ]
		then
			return
		fi

		#bail out if coresight isn't present
		if [ ! -d /sys/bus/coresight ]
		then
			return
		fi

		#coresight
		echo sg > /sys/bus/coresight/devices/coresight-tmc-etr/mem_type

		echo 0 > /sys/kernel/debug/tracing/events/enable
		echo mem > /sys/bus/coresight/devices/coresight-tmc-etr/out_mode
		echo 1 > /sys/bus/coresight/devices/coresight-tmc-etr/enable_sink
		echo 1 > /sys/bus/coresight/devices/coresight-stm/enable_source
		echo 1 > /sys/kernel/debug/tracing/tracing_on

		#SoftIRQs
		echo 1 > /sys/kernel/debug/tracing/events/irq/enable
		#echo 1 > /sys/kernel/debug/tracing/events/irq/filter
		echo 1 > /sys/kernel/debug/tracing/events/irq/softirq_entry/enable
		echo 1 > /sys/kernel/debug/tracing/events/irq/softirq_exit/enable
		echo 1 > /sys/kernel/debug/tracing/events/irq/softirq_raise/enable
		#IRQs
		echo 1 > /sys/kernel/debug/tracing/events/irq/enable
		echo 1 > /sys/kernel/debug/tracing/events/irq/irq_handler_entry/enable
		echo 1 > /sys/kernel/debug/tracing/events/irq/irq_handler_exit/enable
		echo "++++ $0 -> END" > /dev/kmsg
	        ;;
	 esac

         case "$soc_id" in
         "352" | "373")
                echo -n "Starting powerconfig for QCS405/QCS403: "

		echo "++++ $0 -> ENABLE-FTRACE START" > /dev/kmsg
		#Enable FTRACE_ENABLE on SDX24
		#bail out if its perf config
		if [ ! -d /sys/module/msm_rtb ]
		then
			return
		fi

		#bail out if coresight isn't present
		if [ ! -d /sys/bus/coresight ]
		then
			return
		fi

		#coresight
		echo sg > /sys/bus/coresight/devices/coresight-tmc-etr/mem_type

		echo 0 > /sys/kernel/debug/tracing/events/enable
		echo mem > /sys/bus/coresight/devices/coresight-tmc-etr/out_mode
		echo 1 > /sys/bus/coresight/devices/coresight-tmc-etr/enable_sink
		echo 1 > /sys/bus/coresight/devices/coresight-stm/enable_source
		echo 1 > /sys/kernel/debug/tracing/tracing_on

		#SoftIRQs
		echo 1 > /sys/kernel/debug/tracing/events/irq/enable
		#echo 1 > /sys/kernel/debug/tracing/events/irq/filter
		echo 1 > /sys/kernel/debug/tracing/events/irq/softirq_entry/enable
		echo 1 > /sys/kernel/debug/tracing/events/irq/softirq_exit/enable
		echo 1 > /sys/kernel/debug/tracing/events/irq/softirq_raise/enable
		#IRQs
		echo 1 > /sys/kernel/debug/tracing/events/irq/enable
		echo 1 > /sys/kernel/debug/tracing/events/irq/irq_handler_entry/enable
		echo 1 > /sys/kernel/debug/tracing/events/irq/irq_handler_exit/enable
		echo "++++ $0 -> FTRACE-Enable END" > /dev/kmsg

		echo "++++ $0 -> DCC-Enable START" > /dev/kmsg
		DCC_PATH="/sys/bus/platform/devices/b2000.dcc_v2"
		if [ ! -d $DCC_PATH ];
		then
			echo "DCC does not exist on this build."
		        return
		fi

		echo 0 > $DCC_PATH/enable
		echo 2 > $DCC_PATH/curr_list
		echo cap > $DCC_PATH/func_type
		echo sram > $DCC_PATH/data_sink
		echo 1 > $DCC_PATH/config_reset

		#GCC_BIMC
		echo 0x1823000 0x2 > $DCC_PATH/config
		echo 0x1823010 0x1 > $DCC_PATH/config
		echo 0x1823018 0x2 > $DCC_PATH/config
		echo 0x1823024 0x1 > $DCC_PATH/config

		#GCC_SYSTEM_NOC
		echo 0x1826004 0x2 > $DCC_PATH/config

		echo 1 > $DCC_PATH/enable
		echo "++++ $0 -> DCC-Enable END" > /dev/kmsg

		echo "++++ $0 -> END" > /dev/kmsg
	        ;;
	 esac

         case "$soc_id" in
         "187" | "227" | "228" | "229" | "230" | "231")
                echo -n "Starting powerconfig for 9x35: "
                subsyszero=`cat /sys/bus/msm_subsys/devices/subsys0/name`
                subsysone=`cat /sys/bus/msm_subsys/devices/subsys1/name`
                subsystwo=`cat /sys/bus/msm_subsys/devices/subsys2/name`
                if [ "$subsyszero" == "modem" ]
                then
                   subsys=subsys0
                elif [ "$subsysone" == "modem" ]
                then
                   subsys=subsys1
                else
                   subsys=subsys2
                fi
                counter=0
                while [ ${counter} -le 10 ]
                do
                  msstate=`cat /sys/bus/msm_subsys/devices/$subsys/state`
                  if [ "$msstate" == "ONLINE" ]
                  then
                      break
                  fi
                  counter=$(( $counter + 1 ))
                  sleep 1
                done
                echo Y > /sys/module/lpm_levels/system/cpu0/pc/idle_enabled
                echo Y > /sys/module/lpm_levels/system/cpu0/pc/suspend_enabled
                echo Y > /sys/module/lpm_levels/system/cpu0/standalone_pc/idle_enabled
                echo Y > /sys/module/lpm_levels/system/cpu0/standalone_pc/suspend_enabled

                echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
                echo 40000 > /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
                echo 90 > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
                echo 800000 > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
                echo "85 800000:90" > /sys/devices/system/cpu/cpufreq/interactive/target_loads
                echo 40000 > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
                echo 300000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
                echo "done";
                ;;
         esac

        case "$soc_id" in
	"357" | "368")
                echo -n "Starting powerconfig for SDX55: "
                echo N > /sys/module/lpm_levels/parameters/sleep_disabled
                echo ondemand > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
                echo compute > /sys/class/devfreq/soc:qcom,cpubw/governor

                echo mem > /sys/power/autosleep
                echo 10 > /sys/class/devfreq/soc:qcom,cpubw/polling_interval

		echo "++++ $0 -> ENABLE-FTRACE START" > /dev/kmsg
		#Enable FTRACE_ENABLE on SDX55
		#bail out if its perf config
		if [ ! -d /sys/module/msm_rtb ]
		then
			return
		fi

		#bail out if coresight isn't present
		if [ ! -d /sys/bus/coresight ]
		then
			return
		fi

		#coresight
		echo sg > /sys/bus/coresight/devices/coresight-tmc-etr/mem_type

		echo 0 > /sys/kernel/debug/tracing/events/enable
		echo mem > /sys/bus/coresight/devices/coresight-tmc-etr/out_mode
		echo 1 > /sys/bus/coresight/devices/coresight-tmc-etr/enable_sink
		echo 1 > /sys/bus/coresight/devices/coresight-stm/enable_source
		echo 1 > /sys/kernel/debug/tracing/tracing_on

		#SoftIRQs
		echo 1 > /sys/kernel/debug/tracing/events/irq/enable
		echo 1 > /sys/kernel/debug/tracing/events/irq/softirq_entry/enable
		echo 1 > /sys/kernel/debug/tracing/events/irq/softirq_exit/enable
		echo 1 > /sys/kernel/debug/tracing/events/irq/softirq_raise/enable
		#IRQs
		echo 1 > /sys/kernel/debug/tracing/events/irq/enable
		echo 1 > /sys/kernel/debug/tracing/events/irq/irq_handler_entry/enable
		echo 1 > /sys/kernel/debug/tracing/events/irq/irq_handler_exit/enable
		echo 1 > /sys/kernel/debug/tracing/events/workqueue/enable
		echo 1 > /sys/kernel/debug/tracing/events/timer/timer_expire_entry/enable
		echo 1 > /sys/kernel/debug/tracing/events/timer/timer_expire_exit/enable
		echo 1 > /sys/kernel/debug/tracing/events/timer/hrtimer_cancel/enable
		echo 1 > /sys/kernel/debug/tracing/events/timer/hrtimer_expire_entry/enable
		echo 1 > /sys/kernel/debug/tracing/events/timer/hrtimer_expire_exit/enable
		echo 1 > /sys/kernel/debug/tracing/events/timer/hrtimer_init/enable
		echo 1 > /sys/kernel/debug/tracing/events/timer/hrtimer_start/enable

		echo 1 > /sys/kernel/debug/tracing/tracing_on
		echo "++++ $0 -> ENABLE-FTRACE END" > /dev/kmsg

		echo "++++ $0 -> ENABLE-DCC START" > /dev/kmsg
		DCC_PATH="/sys/bus/platform/devices/10a2000.dcc_v2"
		if [ ! -d $DCC_PATH ];
		then
			echo "DCC does not exist on this build."
		        return
		fi

		echo 0 > $DCC_PATH/enable
		echo 2 > $DCC_PATH/curr_list
		echo cap > $DCC_PATH/func_type
		echo sram > $DCC_PATH/data_sink
		echo 1 > $DCC_PATH/config_reset

		#Registers add space
		echo 0x17830400 1 > $DCC_PATH/config #APCS_RSCC_RSC_SEQ_OVERRIDE_START_ADDR_DRV0
		echo 0x17830404 1 > $DCC_PATH/config #APCS_RSCC_RSC_SEQ_BUSY_DRV0
		echo 0x17830408 1 > $DCC_PATH/config #APCS_RSCC_RSC_SEQ_PROGRAM_COUNTER_DRV0
		echo 0xb204520 1 > $DCC_PATH/config #RPMH_PDC_APPS_SEQ_START_ADDR
		echo 0xb201020 1 > $DCC_PATH/config #RPMH_PDC_APPS_SEQ_BUSY_DRV0
		echo 0xb201024 1 > $DCC_PATH/config #RPMH_PDC_APPS_SEQ_DBG_PROGRAM_COUNTER_DRV0
		echo 0x17840400 1 > $DCC_PATH/config #APCS_RSCC_RSC_SEQ_OVERRIDE_START_ADDR_DRV1
		echo 0x17840408 1 > $DCC_PATH/config #APCS_RSCC_RSC_SEQ_PROGRAM_COUNTER_DRV1
		echo 0xb204524 1 > $DCC_PATH/config #RPMH_PDC_APPS_SEQ_OVERRIDE_START_ADDR

		echo 1 > $DCC_PATH/enable
		echo "++++ $0 -> ENABLE-DCC END" > /dev/kmsg
                echo "done";
                ;;
         esac

         case "$soc_id" in
         "458" | "483" | "509")
                echo -n "Starting powerconfig for SDXLEMUR: "
                #Mkdir for coresight-stm protocol folder
                stm_policy=/sys/kernel/config/stp-policy/coresight-stm:p_basic.policy
                mkdir $stm_policy
                chmod 0660 $stm_policy
                chown system:system $stm_policy
                mkdir $stm_policy/default
                chmod 0660 $stm_policy/default
                chown system:system $stm_policy/default
                chown diag:root /dev/byte-cntr

		echo ondemand > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
		#reduce the min frequency once boot is done
		echo 1144 > /sys/class/devfreq/soc:qcom,cpu0-cpu-ddr-lat/min_freq
		echo 10 > /sys/class/devfreq/soc:qcom,cpu0-cpu-ddr-lat/polling_interval

                echo N > /sys/module/lpm_levels/parameters/sleep_disabled
                echo mem > /sys/power/autosleep

                enable_lemur_dcc_config
                enable_lemur_ftrace_event_tracing

                echo "done";
                ;;
         esac

         case "$soc_id" in
         "116" | "142" | "154")
                echo -n "Starting powerconfig for 8x30: "
                echo 1 > /sys/module/pm_8x60/modes/cpu0/power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu1/power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu1/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/standalone_power_collapse/idle_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu1/standalone_power_collapse/idle_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/power_collapse/idle_enabled
                echo 1 > /sys/module/rpm_resources/enable_low_power/L2_cache
                echo 1 > /sys/module/rpm_resources/enable_low_power/pxo
                echo 1 > /sys/module/rpm_resources/enable_low_power/vdd_dig
                echo 1 > /sys/module/rpm_resources/enable_low_power/vdd_mem
                echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
                echo ondemand > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
                chmod 664 /sys/devices/system/cpu/cpu1/online
                echo 10 > /sys/devices/platform/msm_sdcc.3/idle_timeout
                echo 50000 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
                echo 90 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
                echo 1 > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy
                echo 4 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
                echo 10 > /sys/devices/system/cpu/cpufreq/ondemand/down_differential
                echo 70 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_multi_core
                echo 918000 > /sys/devices/system/cpu/cpufreq/ondemand/optimal_freq
                echo 918000 > /sys/devices/system/cpu/cpufreq/ondemand/sync_freq
                echo 80 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_any_cpu_load
                echo 384000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
                echo 384000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
                echo "done"
                ;;
          esac

          case "$soc_id" in
          "126")
                set +e
                echo -n "Starting powerconfig for 8974: "
                echo 2 > /sys/module/lpm_resources/enable_low_power/l2
                echo 1 > /sys/module/lpm_resources/enable_low_power/pxo
                echo 1 > /sys/module/lpm_resources/enable_low_power/vdd_dig
                echo 1 > /sys/module/lpm_resources/enable_low_power/vdd_mem
                echo 1 > /sys/module/pm_8x60/modes/cpu0/power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu1/power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu2/power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu3/power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/power_collapse/idle_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu1/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu2/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu3/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/standalone_power_collapse/idle_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu1/standalone_power_collapse/idle_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu2/standalone_power_collapse/idle_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu3/standalone_power_collapse/idle_enabled
                soc_revision=`cat /sys/devices/soc0/revision`
                if [ "$soc_revision" != "1.0" ]; then
                    echo 1 > /sys/module/pm_8x60/modes/cpu0/retention/idle_enabled
                    echo 1 > /sys/module/pm_8x60/modes/cpu1/retention/idle_enabled
                    echo 1 > /sys/module/pm_8x60/modes/cpu2/retention/idle_enabled
                    echo 1 > /sys/module/pm_8x60/modes/cpu3/retention/idle_enabled
                fi
                echo 0 > /sys/module/msm_thermal/core_control/enabled
                echo 1 > /sys/devices/system/cpu/cpu1/online 2>&1 > /dev/null
                echo 1 > /sys/devices/system/cpu/cpu2/online 2>&1 > /dev/null
                echo 1 > /sys/devices/system/cpu/cpu3/online 2>&1 > /dev/null
                echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
                echo "ondemand" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
                echo "ondemand" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
                echo "ondemand" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
                echo 50000 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
                echo 90 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
                echo 1 > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy
                echo 4 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
                echo 10 > /sys/devices/system/cpu/cpufreq/ondemand/down_differential
                echo 70 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_multi_core
                echo 3 > /sys/devices/system/cpu/cpufreq/ondemand/down_differential_multi_core
                echo 960000 > /sys/devices/system/cpu/cpufreq/ondemand/optimal_freq
                echo 960000 > /sys/devices/system/cpu/cpufreq/ondemand/sync_freq
                echo 80 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_any_cpu_load
                echo 300000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
                echo 300000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
                echo 300000 > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
                echo 300000 > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq
                chown system /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
                chown system /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
                echo 1 > /sys/module/msm_thermal/core_control/enabled
                chown root.system /sys/devices/system/cpu/mfreq
                chmod 220 /sys/devices/system/cpu/mfreq
                chown root.system /sys/devices/system/cpu/cpu1/online
                chown root.system /sys/devices/system/cpu/cpu2/online
                chown root.system /sys/devices/system/cpu/cpu3/online
                chmod 664 /sys/devices/system/cpu/cpu1/online
                chmod 664 /sys/devices/system/cpu/cpu2/online
                chmod 664 /sys/devices/system/cpu/cpu3/online
                echo 1 > /dev/cpuctl/apps/cpu.notify_on_migrate
                echo "done"
                set +e
                ;;
         esac

         case "$soc_id" in
         "145" | "158" | "159" | "198" | "205" | "220" | "221" | "222" | "223" | "224" | "200")
                set +e
                echo -n "Starting powerconfig for 8226: "
                echo 4 > /sys/module/lpm_levels/enable_low_power/l2
                echo 1 > /sys/module/msm_pm/modes/cpu0/power_collapse/suspend_enabled
                echo 1 > /sys/module/msm_pm/modes/cpu1/power_collapse/suspend_enabled
                echo 1 > /sys/module/msm_pm/modes/cpu2/power_collapse/suspend_enabled
                echo 1 > /sys/module/msm_pm/modes/cpu3/power_collapse/suspend_enabled
                echo 1 > /sys/module/msm_pm/modes/cpu0/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/msm_pm/modes/cpu1/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/msm_pm/modes/cpu2/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/msm_pm/modes/cpu3/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/msm_pm/modes/cpu0/standalone_power_collapse/idle_enabled
                echo 1 > /sys/module/msm_pm/modes/cpu1/standalone_power_collapse/idle_enabled
                echo 1 > /sys/module/msm_pm/modes/cpu2/standalone_power_collapse/idle_enabled
                echo 1 > /sys/module/msm_pm/modes/cpu3/standalone_power_collapse/idle_enabled
                echo 1 > /sys/module/msm_pm/modes/cpu0/power_collapse/idle_enabled
                echo 1 > /sys/devices/system/cpu/cpu1/online
                echo 1 > /sys/devices/system/cpu/cpu2/online
                echo 1 > /sys/devices/system/cpu/cpu3/online
                echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
                echo 50000 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
                echo 90 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
                echo 1 > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy
                echo 2 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
                echo 10 > /sys/devices/system/cpu/cpufreq/ondemand/down_differential
                echo 70 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_multi_core
                echo 10 > /sys/devices/system/cpu/cpufreq/ondemand/down_differential_multi_core
                echo 787200 > /sys/devices/system/cpu/cpufreq/ondemand/optimal_freq
                echo 300000 > /sys/devices/system/cpu/cpufreq/ondemand/sync_freq
                echo 80 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_any_cpu_load
                echo 300000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
                chmod 664 /sys/devices/system/cpu/cpu1/online
                chmod 664 /sys/devices/system/cpu/cpu2/online
                chmod 664 /sys/devices/system/cpu/cpu3/online
                # disable msm_hsic_host for 8x26
                if [ -e /sys/bus/platform/drivers/msm_hsic_host ]; then
                    if [ ! -L /sys/bus/usb/devices/1-1 ]; then
                        echo msm_hsic_host > /sys/bus/platform/drivers/msm_hsic_host/unbind
                    fi
                fi
                echo "done"
                set +e
                ;;
         esac

         case "$soc_id" in
          "147" | "161" | "162" | "163" | "164" | "165" | "166")
                set +e
                echo -n "Starting powerconfig for 8610: "
                echo 4 > /sys/module/lpm_levels/enable_low_power/l2
                echo 1 > /sys/module/pm_8x60/modes/cpu0/power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/standalone_power_collapse/suspend_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/standalone_power_collapse/idle_enabled
                echo 1 > /sys/module/pm_8x60/modes/cpu0/power_collapse/idle_enabled
                nr_cpus=`cat /proc/cpuinfo | grep processor | wc -l`
                if [ "$nr_cpus" == "2" ] || [ "$nr_cpus" == "3" ] || [ "$nr_cpus" == "4" ]; then
                    echo -n "Setting CPU1"
                    echo 1 > /sys/module/pm_8x60/modes/cpu1/power_collapse/suspend_enabled
                    echo 1 > /sys/module/pm_8x60/modes/cpu1/standalone_power_collapse/suspend_enabled
                    echo 1 > /sys/module/pm_8x60/modes/cpu1/standalone_power_collapse/idle_enabled
                    echo 1 > /sys/devices/system/cpu/cpu1/online
                    chmod 664 /sys/devices/system/cpu/cpu1/online
                fi
                if [ "$nr_cpus" == "3" ] || [ "$nr_cpus" == "4" ]; then
                    echo -n "Setting CPU2"
                    echo 1 > /sys/module/pm_8x60/modes/cpu2/power_collapse/suspend_enabled
                    echo 1 > /sys/module/pm_8x60/modes/cpu2/standalone_power_collapse/suspend_enabled
                    echo 1 > /sys/module/pm_8x60/modes/cpu2/standalone_power_collapse/idle_enabled
                    echo 1 > /sys/devices/system/cpu/cpu2/online
                    chmod 664 /sys/devices/system/cpu/cpu2/online
                fi
                if [ "$nr_cpus" == "4" ]; then
                    echo -n "Setting CPU3"
                    echo 1 > /sys/module/pm_8x60/modes/cpu3/power_collapse/suspend_enabled
                    echo 1 > /sys/module/pm_8x60/modes/cpu3/standalone_power_collapse/suspend_enabled
                    echo 1 > /sys/module/pm_8x60/modes/cpu3/standalone_power_collapse/idle_enabled
                    echo 1 > /sys/devices/system/cpu/cpu3/online
                    chmod 664 /sys/devices/system/cpu/cpu3/online
                fi
                echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
                echo 50000 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
                echo 90 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
                echo 1 > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy
                echo 4 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
                echo 10 > /sys/devices/system/cpu/cpufreq/ondemand/down_differential
                echo 70 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_multi_core
                echo 3 > /sys/devices/system/cpu/cpufreq/ondemand/down_differential_multi_core
                echo 300000 > /sys/devices/system/cpu/cpufreq/ondemand/optimal_freq
                echo 300000 > /sys/devices/system/cpu/cpufreq/ondemand/sync_freq
                echo 80 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_any_cpu_load
                echo 300000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
                echo "done"
                set +e
                ;;
         esac
         ;;
  stop)
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage pm { start | stop | restart}" >&2
        exit 1
        ;;
esac

# check if we are in recovery-boot mode and disable autosleep
# check for find_recovery_partitions.sh rather than the
# /usr/bin/recovery binary since the recovery binary is
# present in mission-mode bootup on devices that use A/B boot.
if [ -e /etc/init.d/find_recovery_partitions.sh ]; then
    echo -n "In recovery mode; turning off autosleep.." > /dev/kmsg
    echo off > /sys/power/autosleep
fi

exit 0

