#!/bin/sh
#
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# DESCRIPTION: ADB

echo "Switching to composition number 0x4E11"  > /dev/kmsg

if [ "$1" = "y" ]; then
	num="1"
else
	num="0"
fi

if [ "$#" -ge 2 ]; then
	delay=$2
else
	delay="0"
fi

if [ "$#" -ge 3 ]; then
	from_adb=$3
else
	from_adb="n"
fi

if [ -f /sys/class/android_usb/android$num/enable ]; then
	configfs_supported="n"
else
	configfs_supported="y"
fi

run_non_configfs() {
	if [ $from_adb = "n" ]
	then
		pkill adbd
	fi
	echo 0 > /sys/class/android_usb/android$num/enable
	echo 18D1 > /sys/class/android_usb/android$num/idProduct
	echo 4E11 > /sys/class/android_usb/android$num/idVendor
	echo adb > /sys/class/android_usb/android$num/functions
	echo 1 > /sys/class/android_usb/android$num/remote_wakeup
	sleep $delay
	echo 1 > /sys/class/android_usb/android$num/enable
	if [ $from_adb = "n" ]
	then
		/etc/launch_adbd start
	fi
}

run_configfs() {
	echo start > /data/usb_bind_in_progress
	if [ $from_adb = "n" ]
	then
		pkill adbd
		# Give enough time to restart ADBD and open EP0 file node
		sleep 1
	fi
	cd /sys/kernel/config/usb_gadget/g1
	rm os_desc/c* 2> /dev/null
	rm configs/c*/f* 2> /dev/null
	rm -rf configs/c.2 configs/c.3 2> /dev/null
	echo 0x18D1 > idVendor
	echo 0x4E11 > idProduct
	echo "ADB" > configs/c.1/strings/0x409/configuration
	ln -s functions/ffs.adb configs/c.1/f1
	rm -f /data/usb_bind_in_progress
	echo 0x80 > configs/c.1/bmAttributes
	echo "binding UDC with Gadget..." $1
	echo $1 > UDC
	cd /
}

case `. /sbin/usb/target` in
	* )
		if [ $configfs_supported = "y" ]; then
			udcname=`ls -1 /sys/class/udc | head -n 1`
			run_configfs $udcname &
		else
			run_non_configfs &
		fi
		;;
esac
