#!/bin/sh
#
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# DESCRIPTION: DIAG + ADPL

echo "Switching to composition number 0x9105"  > /dev/kmsg

if [ "$#" -ge 3 ]; then
	from_adb=$3
else
	from_adb="n"
fi

run_configfs() {
	echo start > /data/usb_bind_in_progress
	if [ $from_adb = "n" ]
	then
		pkill adbd
		sleep 1
	fi
	cd /sys/kernel/config/usb_gadget/g1
	rm os_desc/c* 2> /dev/null
	rm configs/c*/f* 2> /dev/null
	rmdir configs/c.2/strings/* configs/c.3/strings/* 2> /dev/null
	rmdir configs/c.2 configs/c.3 2> /dev/null
	echo 0x05c6 > idVendor
	echo 0x9105 > idProduct
	echo "DIAG_DPL" > configs/c.1/strings/0x409/configuration
	if [ -e functions/ffs.diag ]; then
		ln -s functions/ffs.diag configs/c.1/f1
	else
		ln -s functions/diag.diag configs/c.1/f1
	fi
	ln -s functions/gsi.dpl configs/c.1/f2
	echo 0xA0 > configs/c.1/bmAttributes
	rm -f /data/usb_bind_in_progress
	echo "binding UDC with Gadget..." $1
	echo $1 > UDC
	cd /
}

case `. /sbin/usb/target` in
	*sdxpoorwills* )
		udcname=`ls -1 /sys/class/udc | head -n 1`
		run_configfs $udcname &
		;;
        * )
		echo "This composition is currently not supported for this target "
		;;
esac
