#!/bin/sh
#
#Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear

# DESCRIPTION: DIAG + QDSS MSM (Trace) + NCM

echo "Switching to composition number 0x9132"  > /dev/kmsg

if [ "$#" -ge 3 ]; then
	from_adb=$3
else
	from_adb="n"
fi

run_configfs() {
	echo start > /tmp/usb_bind_in_progress
	if [ $from_adb = "n" ]
	then
		pkill adbd
		# Give enough time to restart ADBD and open EP0 file node
		sleep 1
	fi
	cd /sys/kernel/config/usb_gadget/g1
	rm os_desc/c* 2> /dev/null
	rm configs/c*/f* 2> /dev/null
	rmdir configs/c.2/strings/* configs/c.3/strings/* 2> /dev/null
	rmdir configs/c.2 configs/c.3 2> /dev/null
	echo 0x05c6 > idVendor
	echo 0x9132 > idProduct
	if [ -e functions/diag.diag/pid ]; then
		echo 0x9132 > functions/diag.diag/pid
	fi
	echo "DIAG_QDSS_NCM" > configs/c.1/strings/0x409/configuration

	if [ -e functions/ffs.diag ]; then
		ln -s functions/ffs.diag configs/c.1/f1
	else
		ln -s functions/diag.diag configs/c.1/f1
	fi

	ln -s functions/$qdss_func configs/c.1/f2
	ln -s functions/ncm.0 configs/c.1/f3

	echo 0x80 > configs/c.1/bmAttributes
	rm -f /tmp/usb_bind_in_progress
	echo "binding UDC with Gadget..." $1
	echo $1 > UDC
	cd /
}

target=`source /sbin/usb/target`
case $target in
	*sxrneo )
		if [ $target == "sxrneo" ]; then
			qdss_func="qdss.qdss_sw"
		else
			qdss_func="qdss.qdss_mdm"
		fi
		udcname=`ls -1 /sys/class/udc | head -n 1`
		run_configfs $udcname &
		;;
	* )
		echo "This composition is not supported"
		;;
esac

