#! /bin/sh
#
#Copyright (c) 2011-2014, The Linux Foundation. All rights reserved.
#
#Redistribution and use in source and binary forms, with or without
#modification, are permitted provided that the following conditions are
#met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#        with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
#WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
#ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
#BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
#BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
#OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
#IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#Changes from Qualcomm Innovation Center are provided under the following license:
#
#Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
#
#Redistribution and use in source and binary forms, with or without
#modification, are permitted (subject to the limitations in the
#disclaimer below) provided that the following conditions are met:
#
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#   * Redistributions in binary form must reproduce the above
#     copyright notice, this list of conditions and the following
#     disclaimer in the documentation and/or other materials provided
#     with the distribution.
#
#    * Neither the name of Qualcomm Innovation Center, Inc. nor the names of its
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
#
#NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE
#GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT
#HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
#WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
#ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
#GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
#IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
#IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

ftrace_event_tracing()
{
    echo "++++ $0 -> ENABLE-FTRACE START" > /dev/kmsg
    #Enable FTRACE_ENABLE on neo
    #bail out if its perf config
    if [ ! -d /sys/module/msm_rtb ]
    then
        return
    fi

    #bail out if coresight isn't present
    if [ ! -d /sys/bus/coresight ]
    then
        return
    fi

    #coresight
    #echo sg > /sys/bus/coresight/devices/coresight-tmc-etr/mem_type

    echo 0 > /sys/kernel/debug/tracing/events/enable
    echo mem > /sys/bus/coresight/devices/coresight-tmc-etr/out_mode
    echo 1 > /sys/bus/coresight/devices/coresight-tmc-etr/enable_sink
    echo 1 > /sys/bus/coresight/devices/coresight-stm/enable_source
    echo 1 > /sys/kernel/debug/tracing/tracing_on

    #SoftIRQs
    echo 1 > /sys/kernel/debug/tracing/events/irq/enable
    echo 1 > /sys/kernel/debug/tracing/events/irq/softirq_entry/enable
    echo 1 > /sys/kernel/debug/tracing/events/irq/softirq_exit/enable
    echo 1 > /sys/kernel/debug/tracing/events/irq/softirq_raise/enable
    #IRQs
    echo 1 > /sys/kernel/debug/tracing/events/irq/enable
    echo 1 > /sys/kernel/debug/tracing/events/irq/irq_handler_entry/enable
    echo 1 > /sys/kernel/debug/tracing/events/irq/irq_handler_exit/enable
    echo 1 > /sys/kernel/debug/tracing/events/workqueue/enable
    echo 1 > /sys/kernel/debug/tracing/events/timer/timer_expire_entry/enable
    echo 1 > /sys/kernel/debug/tracing/events/timer/timer_expire_exit/enable
    echo 1 > /sys/kernel/debug/tracing/events/timer/hrtimer_cancel/enable
    echo 1 > /sys/kernel/debug/tracing/events/timer/hrtimer_expire_entry/enable
    echo 1 > /sys/kernel/debug/tracing/events/timer/hrtimer_expire_exit/enable
    echo 1 > /sys/kernel/debug/tracing/events/timer/hrtimer_init/enable
    echo 1 > /sys/kernel/debug/tracing/events/timer/hrtimer_start/enable

    echo 1 > /sys/kernel/debug/tracing/events/sched/sched_switch/enable

    echo 1 > /sys/kernel/debug/tracing/events/clk/enable
    echo 1 > /sys/kernel/debug/tracing/events/regulator/enable
    echo 1 > /sys/kernel/debug/tracing/events/rpmh/enable

    echo 1 > /sys/kernel/debug/tracing/tracing_on
    echo "++++ $0 -> ENABLE-FTRACE END" > /dev/kmsg
}

set -e

case "$1" in
  start)
        soc_id=`cat /sys/devices/soc0/soc_id`

         case "$soc_id" in
         "525" | "554" )
                echo -n "Starting powerconfig for neo: "
                # Disable Core control
                echo 0 > /sys/devices/system/cpu/cpu0/core_ctl/enable

                # Setting b.L scheduler parameters
                echo 2 > /proc/sys/walt/sched_window_stats_policy
                echo 5 > /proc/sys/walt/sched_ravg_hist_size
                echo 0 > /proc/sys/walt/sched_coloc_busy_hysteresis_enable_cpus

                # cpuset parameters
                echo 0-3 > /dev/cpuset/background/cpus
                echo 0-3 > /dev/cpuset/system-background/cpus

                # Turn off scheduler boost at the end
                echo 0 > /proc/sys/walt/sched_boost

                # Reset the RT boost, which is 1024 (max) by default.
                echo 0 > /proc/sys/kernel/sched_util_clamp_min_rt_default

                # configure governor settings for silver cluster
                echo "walt" > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
                echo 0 > /sys/devices/system/cpu/cpufreq/policy0/walt/down_rate_limit_us
                echo 0 > /sys/devices/system/cpu/cpufreq/policy0/walt/up_rate_limit_us
                echo 90 > /sys/devices/system/cpu/cpufreq/policy0/walt/hispeed_load
                echo 940800 > /sys/devices/system/cpu/cpufreq/policy0/walt/hispeed_freq
                echo 691200 > /sys/devices/system/cpu/cpufreq/policy0/scaling_min_freq
                echo 0 > /sys/devices/system/cpu/cpufreq/policy0/walt/boost
                echo 0 > /sys/devices/system/cpu/cpufreq/policy0/walt/pl

                # configure input boost settings
                echo 940800 0 0 0 0 0 0 0 > /proc/sys/walt/input_boost/input_boost_freq
                echo 120 > /proc/sys/walt/input_boost/input_boost_ms

                # Enable conservative pl
                echo 1 > /proc/sys/walt/sched_conservative_pl

                # configure bus-dcvs
                bus_dcvs="/sys/devices/system/cpu/bus_dcvs"

                for device in $bus_dcvs/*
                do
                    cat $device/hw_min_freq > $device/boost_freq
                done

                for llccbw in $bus_dcvs/LLCC/*bwmon-llcc
                do
                    echo "2288 4577 7110 9155 12298" > $llccbw/mbps_zones
                    echo 4 > $llccbw/sample_ms
                    echo 68 > $llccbw/io_percent
                    echo 20 > $llccbw/hist_memory
                    echo 80 > $llccbw/down_thres
                    echo 0 > $ll-ccbw/guard_band_mbps
                    echo 250 > $llccbw/up_scale
                    echo 1600 > $llccbw/idle_mbps
                    echo 40 > $llccbw/window_ms
                done

                for ddrbw in $bus_dcvs/DDR/*bwmon-ddr
                do
                    echo "762 1720 2086 2597 3879 5931 6515 7980 8136" > $ddrbw/mbps_zones
                    echo 4 > $ddrbw/sample_ms
                    echo 68 > $ddrbw/io_percent
                    echo 20 > $ddrbw/hist_memory
                    echo 80 > $ddrbw/down_thres
                    echo 0 > $ddrbw/guard_band_mbps
                    echo 250 > $ddrbw/up_scale
                    echo 1600 > $ddrbw/idle_mbps
                    echo 48 > $ddrbw/window_ms
                done

                #set s2idle as default suspend mode
                echo s2idle > /sys/power/mem_sleep

                # Enable LPM
                echo N > /sys/devices/system/cpu/qcom_lpm/parameters/sleep_disabled
                ftrace_event_tracing
                ;;
          esac
         ;;
  stop)
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage pm { start | stop | restart}" >&2
        exit 1
        ;;
esac

# check if we are in recovery-boot mode and disable autosleep
# check for find_recovery_partitions.sh rather than the
# /usr/bin/recovery binary since the recovery binary is
# present in mission-mode bootup on devices that use A/B boot.
if [ -e /etc/init.d/find_recovery_partitions.sh ]; then
    echo -n "In recovery mode; turning off autosleep.." > /dev/kmsg
    echo off > /sys/power/autosleep
fi

exit 0

